#!/bin/sh

# soft
# screen=$(xrandr -q | awk '/ connected/ {print $1}')
# xrandr --output $screen --brightness $1

path="/sys/class/backlight/"
path=$path$(ls $path | head -1)

max=$(cat $path/max_brightness)
in=$1
if [ $in -gt 100 ]
then
	in=100
elif [ $in -lt 0 ]
then
	in=0
fi
val=$((max*$in/100))
echo $val > $path/brightness
