#!/bin/sh
if [ "$1" = "" ]
then
	echo 'devices\n' | bluetoothctl | awk '/^Device/ { print $3 }'
	exit
fi

awkcmd='BEGIN { IGNORECASE = 1 } /^device.*'$@'/ { print $2 }'
devmac=$(echo  'devices\n' | bluetoothctl | awk "$awkcmd")

echo "connect $devmac\n" | bluetoothctl
