#!/bin/sh
other=$(screen_others | awk "/$1/" | head -1)
if [ "$other" = "" ]
then
	other=$(xrandr | awk '/0mm x 0mm/ {print $1}' | awk "/$1/")
	if [ "$other" = "" ]
	then
		echo no screen detected
		exit
	fi
fi
xrandr --output $other --off
